package net.searchies.bauen.datagen;

import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricTagProvider;
import net.minecraft.registry.RegistryWrapper;
import net.minecraft.registry.tag.BlockTags;
import net.searchies.bauen.init.ModBlocks;

import java.util.concurrent.CompletableFuture;

public class ModBlockTagProvider extends FabricTagProvider.BlockTagProvider {
    public ModBlockTagProvider(FabricDataOutput output, CompletableFuture<RegistryWrapper.WrapperLookup> registriesFuture) {
        super(output, registriesFuture);
    }

    @Override
    protected void configure(RegistryWrapper.WrapperLookup registries) {
        valueLookupBuilder(BlockTags.PICKAXE_MINEABLE)
            .add(ModBlocks.MOSSY_BRICKS)
            .add(ModBlocks.MOSSY_BRICKS_STAIRS)
            .add(ModBlocks.MOSSY_BRICKS_SLAB)
            .add(ModBlocks.MOSSY_BRICKS_WALL)
            .add(ModBlocks.CRACKED_BRICKS)
            .add(ModBlocks.CRACKED_BRICKS_STAIRS)
            .add(ModBlocks.CRACKED_BRICKS_SLAB)
            .add(ModBlocks.CRACKED_BRICKS_WALL)
            .add(ModBlocks.CHISELED_BRICKS)
            .add(ModBlocks.CHISELED_BRICKS_STAIRS)
            .add(ModBlocks.CHISELED_BRICKS_SLAB)
            .add(ModBlocks.CHISELED_BRICKS_WALL)
            .add(ModBlocks.MOSSY_CHISELED_BRICKS)
            .add(ModBlocks.MOSSY_CHISELED_BRICKS_STAIRS)
            .add(ModBlocks.MOSSY_CHISELED_BRICKS_SLAB)
            .add(ModBlocks.MOSSY_CHISELED_BRICKS_WALL)
            .add(ModBlocks.CRACKED_CHISELED_BRICKS)
            .add(ModBlocks.CRACKED_CHISELED_BRICKS_STAIRS)
            .add(ModBlocks.CRACKED_CHISELED_BRICKS_SLAB)
            .add(ModBlocks.CRACKED_CHISELED_BRICKS_WALL)

            .add(ModBlocks.GOLD_CHAIN)
            .add(ModBlocks.GOLD_LANTERN)
            .add(ModBlocks.GOLD_BARS)
            .add(ModBlocks.CUT_GOLD)
            .add(ModBlocks.CUT_GOLD_STAIRS)
            .add(ModBlocks.CUT_GOLD_SLAB)
            .add(ModBlocks.CUT_GOLD_WALL)
            .add(ModBlocks.CHISELED_GOLD)
            .add(ModBlocks.GOLD_GRATE)
            .add(ModBlocks.GOLD_TRAPDOOR)
            .add(ModBlocks.GOLD_DOOR)
            .add(ModBlocks.GOLD_COINS)
//            .add(ModBlocks.GOLD_HOARD)
//            .add(ModBlocks.GOLD_HOARD_BLOCK)

            .add(ModBlocks.MIXED_COBBLESTONE)
            .add(ModBlocks.MIXED_COBBLESTONE_STAIRS)
            .add(ModBlocks.MIXED_COBBLESTONE_SLAB)
            .add(ModBlocks.MIXED_COBBLESTONE_WALL)

            .add(ModBlocks.INDUSTRIAL_IRON_BLOCK)
            .add(ModBlocks.INDUSTRIAL_IRON_STAIRS)
            .add(ModBlocks.INDUSTRIAL_IRON_SLAB)
            .add(ModBlocks.INDUSTRIAL_IRON_WALL)
            .add(ModBlocks.CUT_INDUSTRIAL_IRON)
            .add(ModBlocks.CUT_INDUSTRIAL_IRON_STAIRS)
            .add(ModBlocks.CUT_INDUSTRIAL_IRON_SLAB)
            .add(ModBlocks.CUT_INDUSTRIAL_IRON_WALL)
            .add(ModBlocks.CARVED_INDUSTRIAL_IRON)
            .add(ModBlocks.INDUSTRIAL_IRON_GRATE)
            .add(ModBlocks.INDUSTRIAL_IRON_TRAPDOOR)
            .add(ModBlocks.INDUSTRIAL_IRON_DOOR)

            .add(ModBlocks.MUD_STAIRS)
            .add(ModBlocks.MUD_SLAB)
            .add(ModBlocks.MUD_WALL)
            .add(ModBlocks.ICE_STAIRS)
            .add(ModBlocks.ICE_SLAB)
            .add(ModBlocks.ICE_WALL)
            .add(ModBlocks.PACKED_ICE_STAIRS)
            .add(ModBlocks.PACKED_ICE_SLAB)
            .add(ModBlocks.PACKED_ICE_WALL)
            .add(ModBlocks.MOSSY_PACKED_MUD)
            .add(ModBlocks.MOSSY_PACKED_MUD_STAIRS)
            .add(ModBlocks.MOSSY_PACKED_MUD_SLAB)
            .add(ModBlocks.MOSSY_PACKED_MUD_WALL)
            .add(ModBlocks.MOSSY_MUD_BRICKS)
            .add(ModBlocks.MOSSY_MUD_BRICKS_STAIRS)
            .add(ModBlocks.MOSSY_MUD_BRICKS_SLAB)
            .add(ModBlocks.MOSSY_MUD_BRICKS_WALL)
            .add(ModBlocks.MOSSY_TUFF_BRICKS)
            .add(ModBlocks.MOSSY_TUFF_BRICKS_STAIRS)
            .add(ModBlocks.MOSSY_TUFF_BRICKS_SLAB)
            .add(ModBlocks.MOSSY_TUFF_BRICKS_WALL)
            .add(ModBlocks.SCULKED_DEEPSLATE_BRICKS)
            .add(ModBlocks.SCULKED_DEEPSLATE_BRICKS_STAIRS)
            .add(ModBlocks.SCULKED_DEEPSLATE_BRICKS_SLAB)
            .add(ModBlocks.SCULKED_DEEPSLATE_BRICKS_WALL)

            .add(ModBlocks.MIDNIGHT_BRICKS)
            .add(ModBlocks.MIDNIGHT_BRICKS_STAIRS)
            .add(ModBlocks.MIDNIGHT_BRICKS_SLAB)
            .add(ModBlocks.MIDNIGHT_BRICKS_WALL)
            .add(ModBlocks.MOSSY_MIDNIGHT_BRICKS)
            .add(ModBlocks.MOSSY_MIDNIGHT_BRICKS_STAIRS)
            .add(ModBlocks.MOSSY_MIDNIGHT_BRICKS_SLAB)
            .add(ModBlocks.MOSSY_MIDNIGHT_BRICKS_WALL)
            .add(ModBlocks.CRACKED_MIDNIGHT_BRICKS)
            .add(ModBlocks.CRACKED_MIDNIGHT_BRICKS_STAIRS)
            .add(ModBlocks.CRACKED_MIDNIGHT_BRICKS_SLAB)
            .add(ModBlocks.CRACKED_MIDNIGHT_BRICKS_WALL)
            .add(ModBlocks.CHISELED_MIDNIGHT_BRICKS)
            .add(ModBlocks.CHISELED_MIDNIGHT_BRICKS_STAIRS)
            .add(ModBlocks.CHISELED_MIDNIGHT_BRICKS_SLAB)
            .add(ModBlocks.CHISELED_MIDNIGHT_BRICKS_WALL)
            .add(ModBlocks.MOSSY_CHISELED_MIDNIGHT_BRICKS)
            .add(ModBlocks.MOSSY_CHISELED_MIDNIGHT_BRICKS_STAIRS)
            .add(ModBlocks.MOSSY_CHISELED_MIDNIGHT_BRICKS_SLAB)
            .add(ModBlocks.MOSSY_CHISELED_MIDNIGHT_BRICKS_WALL)
            .add(ModBlocks.CRACKED_CHISELED_MIDNIGHT_BRICKS)
            .add(ModBlocks.CRACKED_CHISELED_MIDNIGHT_BRICKS_STAIRS)
            .add(ModBlocks.CRACKED_CHISELED_MIDNIGHT_BRICKS_SLAB)
            .add(ModBlocks.CRACKED_CHISELED_MIDNIGHT_BRICKS_WALL)

            .add(ModBlocks.TREATED_BRICKS)
            .add(ModBlocks.TREATED_BRICKS_STAIRS)
            .add(ModBlocks.TREATED_BRICKS_SLAB)
            .add(ModBlocks.TREATED_BRICKS_WALL)
            .add(ModBlocks.MOSSY_TREATED_BRICKS)
            .add(ModBlocks.MOSSY_TREATED_BRICKS_STAIRS)
            .add(ModBlocks.MOSSY_TREATED_BRICKS_SLAB)
            .add(ModBlocks.MOSSY_TREATED_BRICKS_WALL)
            .add(ModBlocks.CRACKED_TREATED_BRICKS)
            .add(ModBlocks.CRACKED_TREATED_BRICKS_STAIRS)
            .add(ModBlocks.CRACKED_TREATED_BRICKS_SLAB)
            .add(ModBlocks.CRACKED_TREATED_BRICKS_WALL)
            .add(ModBlocks.CHISELED_TREATED_BRICKS)
            .add(ModBlocks.CHISELED_TREATED_BRICKS_STAIRS)
            .add(ModBlocks.CHISELED_TREATED_BRICKS_SLAB)
            .add(ModBlocks.CHISELED_TREATED_BRICKS_WALL)
            .add(ModBlocks.MOSSY_CHISELED_TREATED_BRICKS)
            .add(ModBlocks.MOSSY_CHISELED_TREATED_BRICKS_STAIRS)
            .add(ModBlocks.MOSSY_CHISELED_TREATED_BRICKS_SLAB)
            .add(ModBlocks.MOSSY_CHISELED_TREATED_BRICKS_WALL)
            .add(ModBlocks.CRACKED_CHISELED_TREATED_BRICKS)
            .add(ModBlocks.CRACKED_CHISELED_TREATED_BRICKS_STAIRS)
            .add(ModBlocks.CRACKED_CHISELED_TREATED_BRICKS_SLAB)
            .add(ModBlocks.CRACKED_CHISELED_TREATED_BRICKS_WALL)
            .add(ModBlocks.MIXED_BRICKS)
            .add(ModBlocks.MIXED_BRICKS_STAIRS)
            .add(ModBlocks.MIXED_BRICKS_SLAB)
            .add(ModBlocks.MIXED_BRICKS_WALL)
            .add(ModBlocks.MOSSY_MIXED_BRICKS)
            .add(ModBlocks.MOSSY_MIXED_BRICKS_STAIRS)
            .add(ModBlocks.MOSSY_MIXED_BRICKS_SLAB)
            .add(ModBlocks.MOSSY_MIXED_BRICKS_WALL)
            .add(ModBlocks.CRACKED_MIXED_BRICKS)
            .add(ModBlocks.CRACKED_MIXED_BRICKS_STAIRS)
            .add(ModBlocks.CRACKED_MIXED_BRICKS_SLAB)
            .add(ModBlocks.CRACKED_MIXED_BRICKS_WALL)

            .add(ModBlocks.CALCITE_BRICKS)
            .add(ModBlocks.CALCITE_BRICKS_STAIRS)
            .add(ModBlocks.CALCITE_BRICKS_SLAB)
            .add(ModBlocks.CALCITE_BRICKS_WALL)
            .add(ModBlocks.MOSSY_CALCITE_BRICKS)
            .add(ModBlocks.MOSSY_CALCITE_BRICKS_STAIRS)
            .add(ModBlocks.MOSSY_CALCITE_BRICKS_SLAB)
            .add(ModBlocks.MOSSY_CALCITE_BRICKS_WALL)
            .add(ModBlocks.CRACKED_CALCITE_BRICKS)
            .add(ModBlocks.CRACKED_CALCITE_BRICKS_STAIRS)
            .add(ModBlocks.CRACKED_CALCITE_BRICKS_SLAB)
            .add(ModBlocks.CRACKED_CALCITE_BRICKS_WALL)

            .add(ModBlocks.ANDESITE_BRICKS)
            .add(ModBlocks.ANDESITE_BRICKS_STAIRS)
            .add(ModBlocks.ANDESITE_BRICKS_SLAB)
            .add(ModBlocks.ANDESITE_BRICKS_WALL)
            .add(ModBlocks.MOSSY_ANDESITE_BRICKS)
            .add(ModBlocks.MOSSY_ANDESITE_BRICKS_STAIRS)
            .add(ModBlocks.MOSSY_ANDESITE_BRICKS_SLAB)
            .add(ModBlocks.MOSSY_ANDESITE_BRICKS_WALL)
            .add(ModBlocks.CRACKED_ANDESITE_BRICKS)
            .add(ModBlocks.CRACKED_ANDESITE_BRICKS_STAIRS)
            .add(ModBlocks.CRACKED_ANDESITE_BRICKS_SLAB)
            .add(ModBlocks.CRACKED_ANDESITE_BRICKS_WALL)

            .add(ModBlocks.DIORITE_BRICKS)
            .add(ModBlocks.DIORITE_BRICKS_STAIRS)
            .add(ModBlocks.DIORITE_BRICKS_SLAB)
            .add(ModBlocks.DIORITE_BRICKS_WALL)
            .add(ModBlocks.MOSSY_DIORITE_BRICKS)
            .add(ModBlocks.MOSSY_DIORITE_BRICKS_STAIRS)
            .add(ModBlocks.MOSSY_DIORITE_BRICKS_SLAB)
            .add(ModBlocks.MOSSY_DIORITE_BRICKS_WALL)
            .add(ModBlocks.CRACKED_DIORITE_BRICKS)
            .add(ModBlocks.CRACKED_DIORITE_BRICKS_STAIRS)
            .add(ModBlocks.CRACKED_DIORITE_BRICKS_SLAB)
            .add(ModBlocks.CRACKED_DIORITE_BRICKS_WALL)

            .add(ModBlocks.DRIPSTONE_BRICKS)
            .add(ModBlocks.DRIPSTONE_BRICKS_STAIRS)
            .add(ModBlocks.DRIPSTONE_BRICKS_SLAB)
            .add(ModBlocks.DRIPSTONE_BRICKS_WALL)
            .add(ModBlocks.MOSSY_DRIPSTONE_BRICKS)
            .add(ModBlocks.MOSSY_DRIPSTONE_BRICKS_STAIRS)
            .add(ModBlocks.MOSSY_DRIPSTONE_BRICKS_SLAB)
            .add(ModBlocks.MOSSY_DRIPSTONE_BRICKS_WALL)
            .add(ModBlocks.CRACKED_DRIPSTONE_BRICKS)
            .add(ModBlocks.CRACKED_DRIPSTONE_BRICKS_STAIRS)
            .add(ModBlocks.CRACKED_DRIPSTONE_BRICKS_SLAB)
            .add(ModBlocks.CRACKED_DRIPSTONE_BRICKS_WALL)

            .add(ModBlocks.GRANITE_BRICKS)
            .add(ModBlocks.GRANITE_BRICKS_STAIRS)
            .add(ModBlocks.GRANITE_BRICKS_SLAB)
            .add(ModBlocks.GRANITE_BRICKS_WALL)
            .add(ModBlocks.MOSSY_GRANITE_BRICKS)
            .add(ModBlocks.MOSSY_GRANITE_BRICKS_STAIRS)
            .add(ModBlocks.MOSSY_GRANITE_BRICKS_SLAB)
            .add(ModBlocks.MOSSY_GRANITE_BRICKS_WALL)
            .add(ModBlocks.CRACKED_GRANITE_BRICKS)
            .add(ModBlocks.CRACKED_GRANITE_BRICKS_STAIRS)
            .add(ModBlocks.CRACKED_GRANITE_BRICKS_SLAB)
            .add(ModBlocks.CRACKED_GRANITE_BRICKS_WALL)

            .add(ModBlocks.OCEANSLATE)
            .add(ModBlocks.OCEANSLATE_STAIRS)
            .add(ModBlocks.OCEANSLATE_SLAB)
            .add(ModBlocks.OCEANSLATE_WALL)
            .add(ModBlocks.OCEANSLATE_BRICKS)
            .add(ModBlocks.OCEANSLATE_BRICKS_STAIRS)
            .add(ModBlocks.OCEANSLATE_BRICKS_SLAB)
            .add(ModBlocks.OCEANSLATE_BRICKS_WALL)
            .add(ModBlocks.OCEANSLATE_TILES)
            .add(ModBlocks.OCEANSLATE_TILES_STAIRS)
            .add(ModBlocks.OCEANSLATE_TILES_SLAB)
            .add(ModBlocks.OCEANSLATE_TILES_WALL)
            .add(ModBlocks.POLISHED_OCEANSLATE)
            .add(ModBlocks.POLISHED_OCEANSLATE_STAIRS)
            .add(ModBlocks.POLISHED_OCEANSLATE_SLAB)
            .add(ModBlocks.POLISHED_OCEANSLATE_WALL)
            .add(ModBlocks.CRACKED_OCEANSLATE_BRICKS)
            .add(ModBlocks.CRACKED_OCEANSLATE_BRICKS_STAIRS)
            .add(ModBlocks.CRACKED_OCEANSLATE_BRICKS_SLAB)
            .add(ModBlocks.CRACKED_OCEANSLATE_BRICKS_WALL)
            .add(ModBlocks.KELPY_OCEANSLATE_BRICKS)
            .add(ModBlocks.KELPY_OCEANSLATE_BRICKS_STAIRS)
            .add(ModBlocks.KELPY_OCEANSLATE_BRICKS_SLAB)
            .add(ModBlocks.KELPY_OCEANSLATE_BRICKS_WALL);

        valueLookupBuilder(BlockTags.CHAINS).add(ModBlocks.GOLD_CHAIN);
        valueLookupBuilder(BlockTags.LANTERNS).add(ModBlocks.GOLD_LANTERN);
        valueLookupBuilder(BlockTags.BARS).add(ModBlocks.GOLD_BARS);
        valueLookupBuilder(BlockTags.WALLS)
            .add(ModBlocks.MOSSY_BRICKS_WALL)
            .add(ModBlocks.CRACKED_BRICKS_WALL)
            .add(ModBlocks.CHISELED_BRICKS_WALL)
            .add(ModBlocks.MOSSY_CHISELED_BRICKS_WALL)
            .add(ModBlocks.CRACKED_CHISELED_BRICKS_WALL)
            .add(ModBlocks.MIXED_COBBLESTONE_WALL)
            .add(ModBlocks.ICE_WALL)
            .add(ModBlocks.PACKED_ICE_WALL)
            .add(ModBlocks.MUD_WALL)
            .add(ModBlocks.MOSSY_PACKED_MUD_WALL)
            .add(ModBlocks.MOSSY_MUD_BRICKS_WALL)
            .add(ModBlocks.MOSSY_TUFF_BRICKS_WALL)
            .add(ModBlocks.SCULKED_DEEPSLATE_BRICKS_WALL)
            .add(ModBlocks.MIDNIGHT_BRICKS_WALL)
            .add(ModBlocks.MOSSY_MIDNIGHT_BRICKS_WALL)
            .add(ModBlocks.CRACKED_MIDNIGHT_BRICKS_WALL)
            .add(ModBlocks.CHISELED_MIDNIGHT_BRICKS_WALL)
            .add(ModBlocks.MOSSY_CHISELED_MIDNIGHT_BRICKS_WALL)
            .add(ModBlocks.CRACKED_CHISELED_MIDNIGHT_BRICKS_WALL)
            .add(ModBlocks.TREATED_BRICKS_WALL)
            .add(ModBlocks.MOSSY_TREATED_BRICKS_WALL)
            .add(ModBlocks.CRACKED_TREATED_BRICKS_WALL)
            .add(ModBlocks.CHISELED_TREATED_BRICKS_WALL)
            .add(ModBlocks.MOSSY_CHISELED_TREATED_BRICKS_WALL)
            .add(ModBlocks.CRACKED_CHISELED_TREATED_BRICKS_WALL)
            .add(ModBlocks.MIXED_BRICKS_WALL)
            .add(ModBlocks.MOSSY_MIXED_BRICKS_WALL)
            .add(ModBlocks.CRACKED_MIXED_BRICKS_WALL)
            .add(ModBlocks.CALCITE_BRICKS_WALL)
            .add(ModBlocks.MOSSY_CALCITE_BRICKS_WALL)
            .add(ModBlocks.CRACKED_CALCITE_BRICKS_WALL)
            .add(ModBlocks.ANDESITE_BRICKS_WALL)
            .add(ModBlocks.MOSSY_ANDESITE_BRICKS_WALL)
            .add(ModBlocks.CRACKED_ANDESITE_BRICKS_WALL)
            .add(ModBlocks.DIORITE_BRICKS_WALL)
            .add(ModBlocks.MOSSY_DIORITE_BRICKS_WALL)
            .add(ModBlocks.CRACKED_DIORITE_BRICKS_WALL)
            .add(ModBlocks.DRIPSTONE_BRICKS_WALL)
            .add(ModBlocks.MOSSY_DRIPSTONE_BRICKS_WALL)
            .add(ModBlocks.CRACKED_DRIPSTONE_BRICKS_WALL)
            .add(ModBlocks.GRANITE_BRICKS_WALL)
            .add(ModBlocks.MOSSY_GRANITE_BRICKS_WALL)
            .add(ModBlocks.CRACKED_GRANITE_BRICKS_WALL)
            .add(ModBlocks.OCEANSLATE_WALL)
            .add(ModBlocks.OCEANSLATE_BRICKS_WALL)
            .add(ModBlocks.OCEANSLATE_TILES_WALL)
            .add(ModBlocks.POLISHED_OCEANSLATE_WALL)
            .add(ModBlocks.CRACKED_OCEANSLATE_BRICKS_WALL)
            .add(ModBlocks.KELPY_OCEANSLATE_BRICKS_WALL)
            .add(ModBlocks.CUT_GOLD_WALL)
            .add(ModBlocks.INDUSTRIAL_IRON_WALL)
            .add(ModBlocks.CUT_INDUSTRIAL_IRON_WALL);
    }
}
